#!/Users/peter/anaconda/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'pyTools==0.1.0','gui_scripts','videotagger'
__requires__ = 'pyTools==0.1.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pyTools==0.1.0', 'gui_scripts', 'videotagger')()
    )
